### ISSUE TITLE
Breakwa11 已经出面声明，请移除对 @bailing64 的无端指控。

### ISSUE THREAD

**Issue by AspirinGeyer** [Mue11er/re727#4]
Twitter 链接 [https://twitter.com/breakwa11/status/938701088005353473](https://twitter.com/breakwa11/status/938701088005353473)

[Twitter 截图](https://imgur.com/a/BNpdS)

**Comment by kot4ri** [comment]
附药丸时报官推
https://twitter.com/pillnews/status/938630782515474432
